import { NextResponse } from "next/server";
import path from "path";
import fs from "fs";

export async function GET() {
  try {
    // Read the forecast JSON generated by the Python ML pipeline
    const filePath = path.join(process.cwd(), "ml", "output", "forecast_2025.json");

    if (!fs.existsSync(filePath)) {
      // Return a helpful error if pipeline hasn't been run yet
      return NextResponse.json(
        {
          error: "Forecast not generated yet. Run: cd ml && python pipeline.py",
          hint: "The ML pipeline generates ml/output/forecast_2025.json",
        },
        { status: 404 }
      );
    }

    const raw      = fs.readFileSync(filePath, "utf-8");
    const forecast = JSON.parse(raw);

    return NextResponse.json(forecast, {
      headers: {
        // Cache for 1 hour — refresh when pipeline reruns
        "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to read forecast data", detail: String(err) },
      { status: 500 }
    );
  }
}
